# Generated by Django 5.1.6 on 2025-02-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
    ]
