# Generated by Django 5.1.6 on 2025-02-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_populate_user_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='Type',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='user_type',
            field=models.CharField(default='student', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
