# Generated by Django 5.1.6 on 2025-02-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_user_studentuser_user_remove_studentuser_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='user_type',
        ),
    ]
