# Generated by Django 5.1.6 on 2025-02-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_studentuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='Type',
            field=models.CharField(default='student', max_length=15),
        ),
    ]
