# Generated by Django 5.1.6 on 2025-02-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
