# Generated by Django 5.1.6 on 2025-03-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_recruiter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
