# Generated by Django 5.1.6 on 2025-03-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_recruiter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
