# Generated by Django 5.1.6 on 2025-03-03 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_recruiter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_data', models.DateField()),
                ('End_data', models.DateField()),
                ('job_title', models.CharField(max_length=100)),
                ('job_salary', models.FloatField(max_length=20)),
                ('Image', models.FileField(upload_to='')),
                ('job_description', models.TextField(max_length=300)),
                ('job_location', models.CharField(max_length=100)),
                ('job_experience', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Creationdata', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
    ]
