# Generated by Django 5.1.6 on 2025-03-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
