# Generated by Django 5.1.6 on 2025-03-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_rename_name_recruiter_first_name_recruiter_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
