# Generated by Django 5.1.6 on 2025-03-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.recruiter'),
        ),
    ]
